### PR TITLE
COR-340 PARTIAL: Setup Linting for Frontend App

### PR DESCRIPTION
**Pull request by nilueps**

### CODE REVIEW

**Review by internetti — COMMENTED** [review]
is there a command to run this manually? and do you think we could set up a prow task to do this before committing?

**Comment by ludydoo** [comment]
> is there a command to run this manually? and do you think we could set up a prow task to do this before committing?

Unfortunately the prow jobs only run after commiting. But the prow job could "add" a new commit itself with linting. Or, it could "fail fast" if the dev forgot to lint.

**Comment by nilueps** [comment]
Added lint scripts, @internetti

**Pull request merged**
