### PR TITLE
improve case view

### PR DESCRIPTION
**Pull request by ludydoo**

### CODE REVIEW

**Comment by ludydoo** [comment]
Screenshot from 2021-06-22 19-10-46
Screenshot from 2021-06-22 19-10-37

**Review by shinroo — COMMENTED** [review]
I think having the case status as a tag might be better, as this would make it easier to introduce other statuses like `inReview` along the lines of what Abraham showed us today

**Comment by nilueps** [comment]
I agree, a named tag is less ambiguous. But maybe this is something we should ask Cassie about?

**Comment by ludydoo** [comment]
I think that a case could be either done or not done. After that they might have different statuses (think Kanban board). Issues can be in progress, todo, in review, etc. But they are also either done or not done

I imagine that each team would have their own statuses

**Comment by nilueps** [comment]
In that case, maybe at least the shape should change, like 'X' for "not done" and 'V' (a check-mark) for "done". Relying only on color is bad for color-blind folks

**Review by nilueps — COMMENTED** [review]
From the [BS Icons](https://icons.getbootstrap.com/#icons) there's 'x-circle' and 'check-circle'

**Review by nilueps — COMMENTED** [review]
.

**Review by nilueps — CHANGES_REQUESTED** [review]
err, still gettinh the hang of this

**Comment by nilueps** [comment]
I'm gonna merge this because I need to work on these files and I anticipate conflicts.

Please let me know if there's a better solution.

**Pull request merged**
